### PR TITLE
Fix RootDoesDotExit -> RootDoesNotExist.

### LINKED ISSUE #21: Typo in StoreError
`RootDoesDotExit` -> `RootDoesNotExist`

### PR DESCRIPTION
**Pull request by phaazon**
Fix #21.

### CODE REVIEW

File: src/load.rs [hunk 1]
```diff
@@ -283,7 +283,7 @@ impl<C> Storage<C> {
 #[derive(Clone, Debug, Eq, PartialEq)]
 pub enum StoreError {
   /// The root path for a filesystem resource was not found.
-  RootDoesDotExit(PathBuf),
+  RootDoesDotExist(PathBuf),
```
Comment (phaazon) [inline src/load.rs]: `Not`, not `Dot`, you fucking silly!

File: src/load.rs [hunk 2]
```diff
@@ -300,7 +300,7 @@ impl fmt::Display for StoreError {
 impl Error for StoreError {
   fn description(&self) -> &str {
     match *self {
-      StoreError::RootDoesDotExit(_) => "root doesn’t exist",
+      StoreError::RootDoesDotExist(_) => "root doesn’t exist",
```
Comment (phaazon) [inline src/load.rs]: `Not`, not `Dot`, you fucking silly!

File: src/load.rs [hunk 3]
```diff
@@ -509,7 +509,7 @@ impl<C> Store<C> {
     let root = &opt.root;
     let canon_root = root
       .canonicalize()
-      .map_err(|_| StoreError::RootDoesDotExit(root.to_owned()))?;
+      .map_err(|_| StoreError::RootDoesDotExist(root.to_owned()))?;
```
Comment (phaazon) [inline src/load.rs]: `Not`, not `Dot`, you fucking silly!
